// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWKyqjRePnzSGHmfwPaDXbDBLvsT8ERo',
    appId: '1:30677365099:web:33fb5ef8bb5adbfe711c2e',
    messagingSenderId: '30677365099',
    projectId: 'myapp-ff39e',
    authDomain: 'myapp-ff39e.firebaseapp.com',
    storageBucket: 'myapp-ff39e.appspot.com',
    measurementId: 'G-5V087EYLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT_F3u6SIvLA8WqQBksDPTilxN8eUFYKQ',
    appId: '1:30677365099:android:194bc1890eccb380711c2e',
    messagingSenderId: '30677365099',
    projectId: 'myapp-ff39e',
    storageBucket: 'myapp-ff39e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUF8r1MpC4X8lE6uJ9nBGot1_pQTYFvw',
    appId: '1:30677365099:ios:97de8fb788c7efc1711c2e',
    messagingSenderId: '30677365099',
    projectId: 'myapp-ff39e',
    storageBucket: 'myapp-ff39e.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVUF8r1MpC4X8lE6uJ9nBGot1_pQTYFvw',
    appId: '1:30677365099:ios:97de8fb788c7efc1711c2e',
    messagingSenderId: '30677365099',
    projectId: 'myapp-ff39e',
    storageBucket: 'myapp-ff39e.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCWKyqjRePnzSGHmfwPaDXbDBLvsT8ERo',
    appId: '1:30677365099:web:7b8d09fa7d603805711c2e',
    messagingSenderId: '30677365099',
    projectId: 'myapp-ff39e',
    authDomain: 'myapp-ff39e.firebaseapp.com',
    storageBucket: 'myapp-ff39e.appspot.com',
    measurementId: 'G-31W5PSQWM4',
  );
}
